package Enums;

public enum TipoTarea {

    REINICIO,
    INSTALAR_APLICACION,
    DESINSTALAR_APLICACION,
    BLOQUEAR_PANTALLA,
    DESBLOQUEAR_PANTALLA,
    SINCRONIZAR_APLICACIONES,
    ACTUALIZAR_POLITICAS,
    OBTENER_UBICACION,
    FORMATEAR_DISPOSITIVO

}