# Conexión Base de Datos - SIN barras invertidas
#spring.datasource.url=jdbc:postgresql://172.16.1.35:5432/postgres?currentSchema="Monitoreo tablet"
#spring.datasource.username=postgres
#spring.datasource.password=Axe$3128
#spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración Hibernate/JPA
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.default_schema="Monitoreo tablet"

# ESTO EVITA QUE HIBERNATE PASE TODO A MINÚSCULAS (Solución al error del log)
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#spring.jpa.properties.hibernate.globally_quoted_identifiers=true

#spring.security.user.name=admin
#spring.security.user.password=tata2026

server.port=9297

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Axe$3128
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.default_schema=monitoreo tablet